
   
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#  name: Flutter action
#   uses: subosito/flutter-action@v1.5.3


name: Dart

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - name: Getting packages
      working-directory: ./example
      run: flutter pub get
    - name: Checking tests
      working-directory: ./example
      run: flutter test
    - name: Creating apk
      working-directory: ./example
      run: flutter build apk
