name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Getting packages
        working-directory: ./example
        run: flutter pub get
      - name: Getting packages
        working-directory: ./example
        uses: bluefireteam/flutter-gh-pages@v7
          with:
            baseHref: /registration-desk/
